common:
  out_path_: "/home/fyx/ufo_hiahia/src/out/"
  kNumOmpCores_: 8   # cores
  save_: true
  mapping_init_: false
  is_pcd_: false
  skip_: 5

session:
  data_path_: "/media/fyx/Yixin F/Semantic_KITTI/dataset/sequences/00/velodyne/"
  label_path_: "/media/fyx/Yixin F/Semantic_KITTI/dataset/sequences/00/labels/"
  pose_path_: "/media/fyx/Yixin F/Semantic_KITTI/dataset/sequences/00/poses.txt"
  init_: 4   # the num of frame to initialize
  start_: 4320 # the start index in dataset, please check it
  end_: 4535

ssc:
  calib_path_: "calib/"
  seg_path_: "seg/"
  pcd_path_: "pcd/"
  map_path_: "map/"
  evaluate_path_: "evaluate/"

  sensor_height_: 1.73   
  refine_height_: -0.2
  max_z_: 0.8
  min_z_: -1.2
  car_angle_: 120.0
  car_height_: 2.0
  car_square_: 30.0

  min_dis_:  1.5  # /m   
  max_dis_: 30.0  # /m  01 -> 50 on the highway

  min_angle_: 0.0  # /deg
  max_angle_: 360.0

  min_azimuth_: -40.0  # /deg
  max_azimuth_: 80.0

  range_res_: 0.4
  sector_res_: 1.2
  azimuth_res_: 2.0

  max_intensity_: 255.0  # intenisty calibration
  correct_ratio_: 0.8
  correct_radius_: 0.3
  search_num_: 10

  iteration_: 3
  toBeClass_: 10  # the min numbers of points to be one class
  search_c_: 2  # > 1, 2
  intensity_diff_: 2.0
  intensity_cov_: 1.0
  occupancy_: 0.4

  building_: 0  # cluster map
  tree_: 1
  car_: 2

  # about semantic-label: https://github.com/PRBonn/semantic-kitti-api/blob/master/auxiliary/laserscan.py#L238 / https://ask.csdn.net/questions/7650597
  dynamic_label_: [252, 253, 254, 255, 256, 257, 258, 259]   # refer to semantic scan context

  # https://blog.csdn.net/qq_18213223/article/details/104360634
  tr_: [4.276802385584e-04, -9.999672484946e-01, -8.084491683471e-03, -1.198459927713e-02, 
            -7.210626507497e-03, 8.081198471645e-03, -9.999413164504e-01, -5.403984729748e-02, 
            9.999738645903e-01, 4.859485810390e-04, -7.206933692422e-03, -2.921968648686e-01,
            0,                                         0,                                         0,                                             1                                       ]

feature:
  kOneThird_: 0.333
  kLinearityMax_: 288.9
  kPlanarityMax_: 288.9
  kScatteringMax_: 2889.9
  kOmnivarianceMax_: 0.278636
  kAnisotropyMax_: 1248.0
  kEigenEntropyMax_: 0.956129
  kChangeOfCurvatureMax_: 0.99702
  kNPointsMax_: 13200.0

  





  



